# Generated by Django 5.1.4 on 2025-01-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frame', '0004_alter_frame_frameurl'),
        ('user', '0004_rename_userid_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFrame',
            fields=[
                ('customFrame', models.AutoField(primary_key=True, serialize=False)),
                ('customFrameTitle', models.CharField(max_length=30)),
                ('customFrameUrl', models.CharField(max_length=255)),
                ('isShared', models.BooleanField(default=False)),
                ('bookmark', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('frameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frame.frame')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'custom_frames',
            },
        ),
    ]
