# Generated by Django 5.1.4 on 2025-01-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_frame', '0003_rename_custom_frame_customframe_custom_frame_id'),
        ('sticker', '0011_rename_sticker_sticker_sticker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFrameSticker',
            fields=[
                ('custom_frame_sticker_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('sticker_width', models.FloatField()),
                ('sticker_height', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('custom_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='custom_frame.customframe')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sticker.sticker')),
            ],
            options={
                'db_table': 'custom_frame_sticker',
            },
        ),
    ]
