# Generated by Django 5.1.4 on 2025-01-17 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_frame', '0005_customframe_bookmarks'),
        ('user', '0007_rename_user_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('custom_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_frame.customframe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'bookmarks',
            },
        ),
    ]
