version: "3.9"
services:
  traefik:
    image: traefik
    container_name: traefik
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_PATH}/config/traefik.toml:/traefik.toml
      - ${TRAEFIK_PATH}/config/rules:/rules
      - ${TRAEFIK_PATH}/config/acme.json:/acme.json
      - ${TRAEFIK_PATH}/logs:/logs
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 10s
      retries: 30
    restart: always

  whoami:
    image: traefik/whoami
    container_name: whoami
    env_file: .env
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.whoami.rule=Host(`whoami.${URL}`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=lets-encrypt
      - traefik.http.services.whoami.loadbalancer.server.port=80

networks:
  web:
    name: web