services:
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - weathy_network
    env_file:
      - .env

  backend:
    depends_on:
      - db
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/Weathy-Backend/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - weathy_network
    command: >
      sh -c "./wait-for-it.sh mysql:3306 --timeout=30 --strict -- &&
            python manage.py collectstatic --noinput &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn --bind 0.0.0.0:8000 config.wsgi:application"

volumes:
  db_data:
  static_volume:

networks:
  weathy_network:
    driver: bridge