services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/Inframe-Backend/static

    ports:
      - "8000:8000"    
    env_file:
      - .env    
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py makemigrations --noinput &&
            python manage.py migrate --noinput &&
            gunicorn --workers=2 --bind 0.0.0.0:8000 config.wsgi:application"
    develop:
       watch:
        - action: rebuild
          path: requirements.txt
          ignore:
          - .venv
        - action: sync
          path: ./manage.py
          target: /Inframe-Backend/manage.py
    networks:
      - inf
    environment:
      - REDIS_HOST=${EC2_HOST}    
      - CELERY_BROKER_URL=amqp://inframe:inframe@${EC2_HOST}:5672//

  celery:
    build:
      context: .
    command:  >
      celery -A config worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=amqp://inframe:inframe@${EC2_HOST}:5672//
      - REDIS_HOST=${EC2_HOST}
    networks:
      - inf

  celery-beat:
    build:
      context: .
    command:  >
      celery -A config beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=amqp://inframe:inframe@${EC2_HOST}:5672//
      - REDIS_HOST=${EC2_HOST}
    networks:
      - inf

volumes:
  static_volume:
networks:
  inf:
    driver: bridge
