services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - inframe_net
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.backend.loadbalancer.server.port=8000
        - traefik.http.routers.backend.entrypoints=websecure
        - traefik.http.routers.backend.rule=Host(`inframe-server.store`)
        - traefik.http.routers.backend.tls.certresolver=letsencrypt
    env_file:
      - .env
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py makemigrations --noinput &&
            python manage.py migrate --noinput &&
            gunicorn --bind 0.0.0.0:8000 config.wsgi:application"

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=inframe0201@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certificates:/letsencrypt"
    networks:
      - inframe_net

networks:
  inframe_net:

volumes:
  traefik-certificates: