services:
  backend:
    container_name: backend
    image: inframe2/hyeonho2:0.66.13
    volumes:
      - static_volume:/Inframe-Backend/static

    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py makemigrations --noinput &&
            python manage.py migrate --noinput &&
            gunicorn --workers=2 --bind 0.0.0.0:8000 config.wsgi:application"
    develop:
       watch:
        - action: rebuild
          path: requirements.txt
          ignore:
          - .venv
        - action: sync
          path: ./manage.py
          target: /Inframe-Backend/manage.py

volumes:
  static_volume:
