services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    env_file:
      - .env
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--providers.docker.network=inframe-backend_inf"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.metrics.address=:8091"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
      - "--api.dashboard=true"
      - "--accesslog=true"
      - "--accesslog.bufferingsize=100"
      - "--accesslog.format=json"
      - "--accesslog.fields.defaultmode=keep"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--accesslog.fields.headers.names.X-Forwarded-For=keep"
    ports:
      - "80:80"
      - "443:443"
      - "8091:8091"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - inf
    labels:
      logging: "promtail"
      logging_jobname: "traefiklogs"


  backend:
    container_name: backend
    volumes:
      - static_volume:/Inframe-Backend/static
    image: inframe2/hyeonho2:1.1.20250130183936
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py makemigrations --noinput &&
            python manage.py migrate --noinput &&
            gunicorn --workers=2 --bind 0.0.0.0:8000 config.wsgi:application"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.routers.backend.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    environment:
      - REDIS_HOST=${EC2_HOST}
      - CELERY_BROKER_URL=amqp://inframe:inframe@${EC2_HOST}:5672//
    networks:
      - inf

  celery:
    build:
      context: .
    container_name: celery
    command:  >
      sh -c "celery -A config worker --loglevel=info"
    environment:
      - CELERY_BROKER_URL=amqp://inframe:inframe@${EC2_HOST}:5672//
      - REDIS_HOST=${EC2_HOST}

  celery-beat:
    build:
      context: .
    container_name: celery-beat
    command:  >
      sh -c "celery -A config beat --loglevel=info"
    environment:
      - CELERY_BROKER_URL=amqp://inframe:inframe@${EC2_HOST}:5672//
      - REDIS_HOST=${EC2_HOST}

  grafana:
    image: grafana/grafana:9.5.20
    container_name: grafana
    volumes:
      - grafana_data:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.routers.grafana.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"
    networks:
      - inf

volumes:
  static_volume:
  grafana_data:

networks:
  inf:
    driver: bridge