global:
  scrape_interval: 15s #메트릭 수집 인터벌
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: 'prometheus-data' #프로메테우스 "job_name" 이름 (이건 원하시는거 아무거나 해도 차이가 없습니다)
    static_configs: #메트릭 수집 설정
      - targets: ['prometheus-example:9090'] #메트릭을 수집하려는 타겟. <host>:<ip> 형식으로 합니다. 도커에서는 <서비스_이름>:<ip> 입니다.
  - job_name: 'django-data' #job 이름
    static_configs:
      - targets: ['django:8000'] #<서비스_이름>:<포트>
  - job_name: 'traefik-data' # 원하는 이름
    static_configs:
      - targets: [ 'traefik:8091' ] # <host>:<port>