global:
  scrape_interval: 15s #메트릭 수집 인터벌
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'django-data'
    static_configs:
      - targets: ['django:8000']
  - job_name: 'traefik-data'
    static_configs:
      - targets: ['traefik:8091']