# Generated by Django 5.1.4 on 2025-01-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('frame_id', models.AutoField(primary_key=True, serialize=False)),
                ('frame_url', models.FileField(upload_to='frame/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera_width', models.FloatField()),
                ('camera_height', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'frames',
            },
        ),
    ]
