# Generated by Django 5.1.4 on 2025-01-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='camera_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='frame',
            name='camera_width',
            field=models.IntegerField(),
        ),
    ]
