# Generated by Django 5.1.4 on 2025-01-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0002_alter_frame_camera_height_alter_frame_camera_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='camera_height',
            new_name='cameraHeight',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='camera_width',
            new_name='cameraWidth',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='frame_id',
            new_name='frameId',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='frame_url',
            new_name='frameUrl',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
    ]
