# Generated by Django 5.1.4 on 2025-01-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0003_rename_camera_height_frame_cameraheight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frameUrl',
            field=models.URLField(),
        ),
    ]
