# Generated by Django 5.1.4 on 2025-01-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0005_rename_cameraheight_frame_camera_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='id',
            new_name='frame',
        ),
    ]
