# Generated by Django 5.1.4 on 2025-01-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0007_rename_frame_frame_frame_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='basic_frame_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_bg',
            field=models.CharField(default='BGColor1', max_length=512),
            preserve_default=False,
        ),
    ]
