# Generated by Django 5.1.4 on 2025-01-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0008_frame_basic_frame_id_frame_frame_bg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='camera_height',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='camera_width',
        ),
    ]
