# Generated by Django 5.1.4 on 2025-01-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_created_at_user_createdat_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
