# Generated by Django 5.1.4 on 2025-01-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_userid_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
