# Generated by Django 5.1.4 on 2025-01-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_createdat_user_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user',
        ),
    ]
