# Generated by Django 5.1.4 on 2025-01-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_id_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_id',
        ),
    ]
