# Generated by Django 5.1.4 on 2025-01-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0007_rename_createdat_sticker_created_at_and_more'),
        ('user', '0005_rename_createdat_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='user_id',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
