# Generated by Django 5.1.4 on 2025-01-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0008_alter_sticker_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='id',
            new_name='sticker',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='user_id',
            new_name='user',
        ),
    ]
