# Generated by Django 5.1.4 on 2025-01-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0009_rename_id_sticker_sticker_and_more'),
        ('user', '0006_rename_id_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
