# Generated by Django 5.1.4 on 2025-01-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0010_alter_sticker_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='sticker',
            new_name='sticker_id',
        ),
    ]
