# Generated by Django 5.1.4 on 2025-01-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photo_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoUrl',
            field=models.CharField(max_length=1000),
        ),
    ]
