# Generated by Django 5.1.4 on 2025-01-16 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_alter_photo_userid'),
        ('user', '0004_rename_userid_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='userId',
            field=models.ForeignKey(db_column='userId', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
