# Generated by Django 5.1.4 on 2025-01-16 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_alter_photo_userid'),
        ('user', '0004_rename_userid_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photoId',
            new_name='photo_id',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photoUrl',
            new_name='photo_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='userId',
        ),
        migrations.AddField(
            model_name='photo',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
