# Generated by Django 5.1.4 on 2025-01-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_rename_createdat_photo_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user_id',
            new_name='user',
        ),
    ]
