# Generated by Django 5.1.4 on 2025-01-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_rename_photo_id_photo_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='photo_id',
        ),
    ]
