name: Deploy Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # 코드 클론
        uses: actions/checkout@v4

      - name: Copy docker-compose file to Server # docker-compose 파일 복사
        uses: appleboy/scp-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: docker-compose-prod.yml
          target: /home/ubuntu/Inframe-Backend

      - name: Copy .env file to Server # .env 파일 복사
        uses: appleboy/scp-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .env
          target: /home/ubuntu/Inframe-Backend

      - name: Deploy to Server # Docker Compose 실행
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Inframe-Backend
            docker compose -f docker-compose-prod.yml --env-file .env pull
            docker compose -f docker-compose-prod.yml --env-file .env up -d

      - name: Clean up files in Server # 서버에서 파일 삭제
        if: always()
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -f /home/ubuntu/Inframe-Backend/docker-compose-prod.yml
            rm -f /home/ubuntu/Inframe-Backend/.env
