name: Deploy Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub Actions 워크플로 시작 시 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. docker-compose.yml을 서버로 복사
      - name: Copy docker-compose-prod.yml to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: docker-compose-prod.yml
          target: /home/ubuntu/

      # 3. .env 파일을 서버로 복사
      - name: Copy .env file to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .env
          target: /home/ubuntu/

      # 4. 서버에서 Docker Compose 실행
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/
           docker compose -f docker-compose-prod.yml pull
           docker compose -f docker-compose-prod.yml up -d
