name: Deploy Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            git clone https://github.com/Team-Inframe/Inframe-Backend.git
            cd Inframe-Backend
            docker compose -f docker-compose-prod.yml down
            docker compose -f docker-compose-prod.yml up -d
            rm -rf Inframe-Backend