name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Show build number
      run: |
        echo "Build Number: ${{ github.run_number }}" # 빌드 넘버는 런 넘버 입니다
    - name: Show pull request number
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo "PR Number: ${{ github.event.pull_request.number }}"
    - name: Get PR Number for Develop Branch Merge
      id: get_pr_number
      if: github.ref == 'refs/heads/develop'
      run: |
        PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state closed --json number,mergeCommit --jq ".[] | select(.mergeCommit.oid == \"${{ github.sha }}\") | .number")
        echo "PR_NUMBER=${PR_NUMBER}"
        echo "PR_NUMBER"="${PR_NUMBER}" >> $GITHUB_OUTPUT

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set Docker Image Tag
      id: set_docker_image_tag
      env:
        PR_NUMBER: ${{ steps.get_pr_number.outputs.PR_NUMBER }}
      run: |
        if [ "${{ github.ref_name }}" == "develop" ]; then 
          DOCKER_IMAGE_TAG="1.1.$PR_NUMBER"
        else # 그냥 풀 리퀘 요청인 경우
          DOCKER_IMAGE_TAG="0.${{ github.event.pull_request.number }}.${{ github.run_number }}"
        fi
        echo "Docker Image Tag: $DOCKER_IMAGE_TAG"
        echo "DOCKER_IMAGE_TAG"="${DOCKER_IMAGE_TAG}" >> $GITHUB_OUTPUT
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      env:
        DOCKER_IMAGE_TAG: ${{ steps.set_docker_image_tag.outputs.DOCKER_IMAGE_TAG }}
      run: |
        
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hyeonho2:$DOCKER_IMAGE_TAG .
        docker push ${{ secrets.DOCKER_USERNAME }}/hyeonho2:$DOCKER_IMAGE_TAG
